---
fake_backend_source_repo: "https://github.com/sahibmartial/fake-backend.git"
fake_backend_source_branch: "master"
fake_backend_image_tag: "V2-projet4"

home: "/home/centos"
volume_database: "/srv/db-data"

ip_addr_preprod: "54.85.180.1"
ip_addr_prod: "100.27.31.130"
port_app: "8181"

login_app: "{{ vault_login_app  }}"
password_app: "{{ vault_password_app }}"

#secret data vaulted
github_private_key: "{{ vault_github_private_key }}"
docker_hub_login: "{{ vault_docker_hub_login }}"
docker_hub_email: "{{ vault_docker_hub_email }}"
docker_hub_password: "{{ vault_docker_hub_password }}"
